name: Post Release

on:
  release:
    types:
      - published

# based on https://github.com/apexskier/github-release-commenter/issues/545#issuecomment-2513388057
permissions:
  issues: write
  pull-requests: write

jobs:
  post_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "npm_version=$(npm pkg get version | tr -d '"')" >> "$GITHUB_ENV"
      - uses: apexskier/github-release-commenter@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment-template: |
            :tada: This is included in version {release_link} :tada:

            The release is available on:

            * [GitHub releases](https://github.com/johnnyreilly/azdo-npm-auth/releases/tag/{release_tag})
            * [npm package (@latest dist-tag)](https://www.npmjs.com/package/azdo-npm-auth/v/${{ env.npm_version }})

            Cheers! 📦🚀
